title: Jake Haines | Data
description: Data Engineer driven by systems thinking and curiosity about the world. I take pride in my knowledge 
  across disciplines like scientific research, automotive, sensors, and audio, allowing me to understand data in 
  context and leverage it effectively.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: