name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main]  # or your source branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Match your Gemfile's Ruby version
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match your Node.js version
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Install Ruby dependencies
        run: bundle install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site