name: Build and Deploy Jekyll Site

permissions:
  contents: write

on:
  push:
    branches: [main]  # or your source branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Match your Gemfile's Ruby version
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match your Node.js version
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Install Ruby dependencies
        working-directory: ./site
        run: bundle install

      - name: Jekyll install
        run: npm run jekyll:install

      - name: Build Jekyll site
        working-directory: ./site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git fetch origin gh-pages
          git switch gh-pages || git checkout --orphan gh-pages
          git rm -rf . || true
          cp -r _site/* .
          git add .
          git commit -m "deploy: $GITHUB_SHA" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}